#!/usr/bin/env bash
# DikaRoute — Vercel build command
#
# Vercel builds Next.js serverless functions with a plain `next build` (it does
# NOT use `output: standalone`). The repository's default `build` script
# (scripts/build/build-next-isolated.mjs) assembles a standalone bundle for
# Docker/local/npm — that is the wrong target on Vercel and would be wasted work.
#
# So the Vercel build runs `next build` directly, letting Vercel's framework
# adapter emit serverless functions. Key behaviour relied upon:
#   - NEXT_PHASE=phase-production-build makes DikaRoute's DB layer (`isBuildPhase`)
#     boot with an in-memory SQLite — no fs writes during the build.
#   - `globalThis.caches` exists on the Vercel runtime, so `isCloud` is true at
#     runtime too → in-memory DB instead of a persistent SQLite file.
#   - `.source/` (fumadocs MDX output) is regenerated by Next's build via the
#     createMDX() plugin in next.config.mjs.
#
# Bundler choice — webpack, NOT Turbopack:
#   Turbopack is the Next 16 default and is faster on big hosts (benchmarked:
#   ~7 min on ubuntu-latest's 4 vCPU / 16 GB). But its native Rust heap is
#   UNBOUNDED (--max-old-space-size does not apply), and on small hosts it
#   memory-thrashes the box and freezes with zero build output for hours —
#   documented 3x on a 7.7 GB / 4-core box (see next.config.mjs
#   webpackBuildWorker note and #6409), and reproduced on Vercel's default
#   Elastic build machine (4 vCPU / 8 GB): the deployment sat at
#   "Creating an optimized production build ..." for the full 45-minute limit.
#   The webpack pass is bounded and completes in ~8-14 min on the same 8 GB
#   profile. So Vercel defaults to `--webpack`; set
#   `DIKAROUTE_USE_TURBOPACK=1` (project env var) to opt back into Turbopack
#   when the Vercel build machine is upgraded (e.g. 16 vCPU / 64 GB Premium).
set -euo pipefail

node -v

export NEXT_TELEMETRY_DISABLED=1

# Keep the DB layer and env resolvers from writing to a HOME data dir during build.
# isCloud/isBuildPhase already short-circuit fs writes, but be explicit.
export DATA_DIR="${DATA_DIR:-/tmp/dikaroute-vercel}"

# Vercel's Next.js adapter discovers the build by the standard ".next" directory
# (next.config defaults to ".build/next" when NEXT_DIST_DIR is unset). Point it at
# the standard location so Vercel's serverless + static output is emitted correctly.
export NEXT_DIST_DIR=".next"

# NEXT_DIST_DIR relocates the build; keep basePath empty for a root deploy.
export DIKAROUTE_BASE_PATH=""

# The webpack production pass bundles the whole server graph and peaks ~3.9 GB
# on a clean module graph, overflowing V8's default ~2 GB ceiling on
# memory-constrained machines (that is why build-next-isolated.mjs raises the
# heap). Vercel runs `next build` directly (no wrapper), so set a bounded heap
# here: 5 GB gives the compile pass headroom while leaving room for the
# static-generation workers on Vercel's 8 GB Elastic build machine. Tune via
# DIKAROUTE_BUILD_MEMORY_MB if a build machine profile changes.
export NODE_OPTIONS="$(printf '%s' "${NODE_OPTIONS:-}") --max-old-space-size=${DIKAROUTE_BUILD_MEMORY_MB:-5120}"

if [ "${DIKAROUTE_USE_TURBOPACK:-0}" = "1" ]; then
  BUNDLER_FLAG="--turbopack"
else
  BUNDLER_FLAG="--webpack"
fi

echo "[vercel-build] Running \`next build ${BUNDLER_FLAG}\` for Vercel serverless output..."
npx next build ${BUNDLER_FLAG}

echo "[vercel-build] Build finished."