#!/usr/bin/env bash
# DikaRoute — Vercel build command
#
# Vercel builds Next.js serverless functions with a plain `next build` (it does
# NOT use `output: standalone`). The repository's default `build` script
# (scripts/build/build-next-isolated.mjs) assembles a standalone bundle for
# Docker/local/npm — that is the wrong target on Vercel and would be wasted work.
#
# So the Vercel build runs `next build` directly, letting Vercel's framework
# adapter emit serverless functions. Key behaviour relied upon:
#   - NEXT_PHASE=phase-production-build makes DikaRoute's DB layer (`isBuildPhase`)
#     boot with an in-memory SQLite — no fs writes during the build.
#   - `globalThis.caches` exists on the Vercel runtime, so `isCloud` is true at
#     runtime too → in-memory DB instead of a persistent SQLite file.
#   - `.source/` (fumadocs MDX output) is regenerated by Next's build via the
#     createMDX() plugin in next.config.mjs.
#
# Memory: raise the V8 heap like the local webpack wrapper does. Turbopack is the
# default production bundler (fast, but native — unbounded by --max-old-space-size).
set -euo pipefail

node -v

export NEXT_TELEMETRY_DISABLED=1

# Keep the DB layer and env resolvers from writing to a HOME data dir during build.
# isCloud/isBuildPhase already short-circuit fs writes, but be explicit.
export DATA_DIR="${DATA_DIR:-/tmp/dikaroute-vercel}"

# Vercel's Next.js adapter discovers the build by the standard ".next" directory
# (next.config defaults to ".build/next" when NEXT_DIST_DIR is unset). Point it at
# the standard location so Vercel's serverless + static output is emitted correctly.
export NEXT_DIST_DIR=".next"

# NEXT_DIST_DIR relocates the build; keep basePath empty for a root deploy.
export DIKAROUTE_BASE_PATH=""

echo "[vercel-build] Running \`next build\` for Vercel serverless output..."
npx next build --turbopack

echo "[vercel-build] Build finished."